workdir: "/users/cicd"
# Define the OpenShift name/ip:port address
openshift: 10.1.2.2:8443
# Your OpenShift credentials
username: openshift-dev
password: devel
# Administrative credentials
# To login as system:admin and no password
#admin_username: system:admin
#admin_password: "''"
admin_username: admin
admin_password: admin
# Customize the domain of the project
domain: rhel-cdk.10.1.2.2.nip.io
# If your application uses a special SCC, uncomment the following line to adjust the SCC
adjust_scc: false
# Define the name of the OpenShift cicd main project
cicd_project_name: cicd
cicd_template_name: cicd-template.yaml

# Project definition - You don't need to change anything here
cicd_projects:
  - name: cicd
    displayname: ci/cd
    description: A CI/CD project
  - name: dev
    displayname: dev
    description: Development space to host dev apps
  - name: stage
    displayname: stage
    description: Staging space to host staging apps
