workdir: "/users/helloworld-msa"
# Define the OpenShift name/ip:port address
openshift: 10.1.2.2:8443
# Your OpenShift credentials
username: openshift-dev
password: devel
# Administrative credentials
# To login as system:admin and no password
#admin_username: system:admin
#admin_password: "''"
admin_username: admin
admin_password: admin
# Customize the domain of the project
domain: rhel-cdk.10.1.2.2.nip.io
# If your application uses an special SCC, uncomment the following line to adjust the SCC
adjust_scc: false
# Define the name of the OpenShift project
project_name: helloworld-msa

# Optional parts
# Some users might have the MSA modules cloned locally already. For those cases, make this 'false' and
# we'll not attempt to clone it again
clone_modules: false

# Define if we should deploy CI/CD capabilities with Jenkins
deploy_jenkins: false
#Define if we should deploy Hystrix and Kubeflix
deploy_hystrix: true
#Define if we should deploy ZipKin
deploy_zipkin: true
#Define if we should deploy Hawkular APM
deploy_hawkular_apm: true
#Define if we should deploy Keycloak for SSO
deploy_keycloak: false

build_project: false

# Project definition - You don't need to change anything here
msa_projects:
  - name: hola
    project: java
    hystrix: true
    probe: http://:8080/api/health
    jolokia: false #This project doesn't support Jolokia
    sso_support: true
    build: false
  - name: frontend
    project: node
    hystrix: false
    probe: False
    jolokia: false #This project doesn't support Jolokia
    sso_support: true
    build: false
  - name: bonjour
    project: node
    hystrix: false
    probe: http://:8080/api/health
    jolokia: false #This project doesn't support Jolokia
    sso_support: true
    build: false
  - name: api-gateway
    project: java
    hystrix: true
    probe: http://:8080/health
    jolokia: false
    sso_support: false
    build: false
  - name: ola
    project: java
    hystrix: true
    probe: http://:8080/api/health
    jolokia: false
    sso_support: true
    build: false
  - name: aloha
    project: java
    hystrix: true
    probe: http://:8080/api/health
    jolokia: false
    sso_support: true
    build: false
